apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTVFzUlhVblY5OTB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBM01EY3lNekl3TkRWYUZ3MHpOakEzTURReU16STFORFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMrNXd4dERqdUNoQVRsbmdPZms5T2RidG5waVlXL2hqWFZZdW9LMHJTUmNWWWxhQTgyUlNPWTNmVngKU1lSNlFmWXVrQ2lPREROdWJpZm1iY1dqNEE2Zm5OMnpIdGQ3bE9HNkZwZnFnQ2UyMFJKeU1JeHVKT05HWVRQbQpMVjBHcEdZNTcrNnVTVDZobGJFTUh6N3dGaDlKT0h3QVpkU2JxeTlvV016T1k2QnI2S3U4bytLTzR0TEJyZ2g0CnRnUlhkaktKc3JDM2lvN0lDbHNXVlkvY1Z5Q2llazAvdStsZzlSelRpak1CMTRsbjBlQzZVMVlNK3lVSEsySnEKSldlK2RteG1ubFd4QmNlN0didmMwSVlQTEpNOXV0K0ZxU0FWZlg2bENMZ3JOSmRSQndsR3dOTnQ2VHdycit4Qwo2VThsTkVDalBGUnlBNTlCVmNveGl5RHlxeEFiQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSUEZ5NTBsQ1FKaThqaXg4aWtjQnM3WWlnL1B6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ25WOG9hSWdvbApzOTRpTEVzM3B5S0lteGx3WTFkYk1EVUlvRDRWYVZMSWhyWjJBT3pRS2hIVS8xdTdrSjRGQ1NLbEpKTHpTZWxECjRmWWRMYmdUTWJsc1g0a3RCdEVvckRFYi9SY3pOY3RjdVlFR2dyY1BIQ1RBY3dxVkpoV0tmWGdmY3F1Z05hU2EKdG9oeW5Sdkc0MTFQWFQyeDhSMHlZVUlCS2pIc2daczlpSEFFOXZPb3Y5eWxEdk53Wml2TEJ6d253eHFMMG10eQpFdTM3ZzlMN3lvWEZWN1l6T3g1UmZ6eHlGOHl0RENRV1ZGUnorbVdPdS93Qk50dnU4NVRXUmF1ZXduenRtMmsxCmRvZEZuNGVHMElFN3ExZHlFT2REaWppOFBLdHh4YnU2c04zODN4b2NDSnFWbTd6Z05xQXo5b1hUdUVjNk5IZWwKdUxuTDZVTzQwMzBxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0ed794cf-3bd5-4c8c-bf18-2587a0300024.us-ord-5-gw.linodelke.net:443
  name: lke627526

users:
- name: lke627526-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Il95VFk2OU9lUWVMOXN4ejZaMDM0cS0wUzNEWWlKUmJaYThodXJfcGJ0akkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tY2I4ZmMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYzg0MmQ2MTYtYzJmNC00ZGJjLWE0MzQtNGY0YTAxZWZjMGQxIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.KusxP1PVd9ufK7iQ7Z1jNhB8_CeqU5or281fpBNTKuSWpt9ofSy8DCe1enaP827Ugco5ByGrun1kH6kSwsxlhdEF85u7aZOLIoBNpYGLFfsK8ywJZ3T5PFqD-UM7MhnapbzPSGBr9f7ColQ6YPIl0kMHi_LSG7RiS3qiieMivKhzhfsa-9dwM3ruelvj7akxiDxjuP-1RDm0MOYNx7UeClfgsNGp5XH7N5IDg6pgC4I-hPquGxZK2lbMCRNEJDPAkoxGHhKFX2MDbkU3keIUf6s_NBnQMhtMeJCbFBEqTqEg9JhU09Augo0XGUmCZMvL3edDs9S0i_vux_gpUYGjQw

contexts:
- context:
    cluster: lke627526
    namespace: default
    user: lke627526-admin
  name: lke627526-ctx

current-context: lke627526-ctx
